server:
  port: 9000

spring:
  application:
    name: eureka-ribbon-consumer
eureka:
  client:
    registerWithEureka: true 
    fetchRegistry: true
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  server:
    enable-self-preservation: false
ribbon:
  eureka:
    enabled: true
